### ISSUE TITLE
Documentation does not build with doxygen 1.8.17

### ISSUE THREAD

**Issue by stwirth** [Ekumen-OS/beluga#227]
### Bug description
_A clear and concise description of what the bug is._

```
/mypath/src/beluga/beluga/include/beluga/algorithm/sampling.hpp:202: error: \cite command to 'fox2001adaptivekldsampling' does not have an associated number (warning treated as error, aborting now)
Exiting...
```

**Platform (please complete the following information):**
 - OS: Ubuntu focal
 - `Beluga` version: ed7dfe38bcab566a900b636378e7dbf05981120a
```
$ doxygen -v
1.8.17
```
That's the standard version that ships with Ubuntu focal.

### How to reproduce
_List steps to reproduce the issue:_
1. catkin_make_isolated

_Code snippets or minimal examples are always helpful, if not necessary._

**Expected behavior**
_A clear and concise description of what you expected to happen._
see above

**Actual behavior**
_A clear and concise description of what actually happened._
no error

### Additional context
_Any other information you think could be meaningful to this issue._

**Comment by stwirth** [comment]
And `/mypath/src/beluga/beluga/include/beluga/sensor/beam_model.hpp:39`

**Comment by stwirth** [comment]
`/mypath/beluga/beluga/include/beluga/sensor/beam_model.hpp:62`

**Comment by stwirth** [comment]
Happens on all `\cite` tags :)

**Comment by hidmic** [comment]
I don't think it's an issue with the version. Our Ubuntu Focal containers have the exact same version. It's something else. Any other relevant error @stwirth?

**Comment by stwirth** [comment]
Nope, I removed all lines containing \cite and it built fine.

**Comment by nahueespinosa** [comment]
Hmm, I can't reproduce this either.
